on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 24 23 * * *
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: self-hosted
    env:
      SEMGREP_APP_TOKEN: ${{ 9af663b7776a67e5d5680a0bc4fdc2fd05dc61d8981c88f00568af56aa10cf5c }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: semgrep ci
